sudo: false
language: ruby

script: bundle exec ruby spec/unicode_types_spec.rb

rvm:
- ruby-head
- 2.4.1
- 2.3.4
- 2.2
- 2.1
- 2.0
- jruby-head
- jruby-9.1.12.0

cache:
- bundler

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: 2.0
#   fast_finish: true

